//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_5_6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkman
    {
        public Checkman()
        {
            this.Order = new HashSet<Order>();
        }
    
        public string Name { get; set; }
        public string telephone { get; set; }
        public string adress { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
