//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_5_6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bazaEntities3 : DbContext
    {
        public bazaEntities3()
            : base("name=bazaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checkman> Checkman { get; set; }
        public virtual DbSet<Flower> Flower { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
