//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_5_6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Flower { get; set; }
        public string Checkman { get; set; }
        public int Stok { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string volume { get; set; }
        public string oplata { get; set; }
    
        public virtual Checkman Checkman1 { get; set; }
        public virtual Flower Flower1 { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
