//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_5_6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string idFlower { get; set; }
        public string volume { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idStock { get; set; }
    
        public virtual Flower Flower { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
